[template]
src = "newrelic.ini.tmpl"
dest = "/etc/php/7.0/mods-available/newrelic.ini"
mode = "0644"

keys = [
    "/php/newrelic/license/key",
    "/php/newrelic/appname",
    "/php/newrelic/framework",
    "/php/newrelic/port"
]
